language: java

before_script:
  - wget -c http://download.libsodium.org/libsodium/releases/libsodium-0.4.1.tar.gz
  - tar xzvf libsodium-0.4.1.tar.gz
  - pushd libsodium-0.4.1 && mkdir vendor
  - ./configure --prefix=`pwd`/vendor
  - make && make install
  - popd

script: "LD_LIBRARY_PATH=/home/travis/build/joshjdevl/kalium-jni/libsodium-0.4.1/vendor/lib"

env: JAVA_OPTS="-Djava.library.path=/home/travis/build/joshjdevl/kalium-jni/libsodium-0.4.1/vendor/lib"

jdk:
  - oraclejdk7
  - openjdk6

after_success:
  - rm -rf libsodium-0.4.1*
