language: android
env:
  matrix:
  - ANDROID_API=android-10 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-15 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-16 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-17 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-18 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-19 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-21 ANDROID_ABI=armeabi-v7a
  global:
  - secure: "gV/l8tket121k0Um4nJmvfChezXCQH80AV+cxdBZcp1q/zAcwOwceAMJCzTIho7NlZvr9TEAoUvJpglGhdv/xr59S62OLjooXXwGIWzcs5vJGiAurPiH/XJwGw/2tusMLp5PH7zxo1/3kNu97ate/nlqa/CMuTYwwxVpn/4dJMw="
  - secure: "zcbQlAhYrhHm+/9pmROQHFGfFXSGx8tWrBO0qTEe1D1AId8JhtDwY9I3uXCcX5y4l4d1eg4G6G2q0Nic6SyqKXNFF88HeLiazRmeajaAvTLfU7dEWIzWKwyFCK1VchXkI2al1ApDKXtoaC4m13Em0GzhIxb74gShYmIhEvzANiM="
  - secure: "bqDnpaF/lMp4esJpYU68zzybn3urG/1T6fyzOgxo/RFYtiaYkV3a1Kf79wnABDgDfZHQ4rvkO2ceRdANAGySpfkazRV5zSJIri3X2FpsTPo5wVtC9PFtGSWI6skGxVwdI2C2zMdstm8+Lmiv/vBkg8Q8Gd2b2ofkBmKnUxTHtMk="
matrix:
  allow_failures:
  - env: ANDROID_API=android-21 ANDROID_ABI=x86_64
  - env: ANDROID_API=android-24 ANDROID_ABI=x86_64
os:
- linux
sudo: required
before_install:
- travis_wait 60 ./dependencies.sh
before_script:
- . ./setenv.sh
script:
- travis_wait 30 ./travis.sh
after_failure:
- cat emulator.log
- cat logcat.log
after_success:
- gradle uploadArchives
- mvn deploy --settings settings.xml
